### ISSUE TITLE
MIPS64: elf_getdata() failed: Invalid section descriptor

### ISSUE THREAD

**Issue by emaste** [emaste/elftoolchain#1]
Trying to build pkg on MIPS, using elftoolchain strip instead of GNU's due to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=191587 produces the following:

```
libtool: install: strip --strip-unneeded /usr/ports/ports-mgmt/pkg/work/stage/usr/local/lib/libpkg.so.3.0.0
strip: elf_getdata() failed: Invalid section descriptor
```

I suspect this is due to the following section:

```
entry: 1
        sh_name: .MIPS.options
        sh_type: ERROR: SHT 0x7000000d NOT DEFINED
        sh_flags: 
        sh_addr: 0x120
        sh_offset: 288
        sh_size: 3040
        sh_link: 0
        sh_info: 0
        sh_addralign: 8
        sh_entsize: 1
```

0x7000000d is SHT_MIPS_OPTIONS

(Entered as a github bug while waiting to recover my sourceforge.net account.)
